[package]
name = "hello-solana"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.14"

[dev-dependencies]
solana-program-test = "1.18.14"
solana-sdk = "1.18.14"

[lib]
crate-type = ["cdylib", "lib"]